### ISSUE TITLE
화면별 분석 & 스토리 작성

### ISSUE THREAD

**Issue by yellow2041** [yellow2041/clone-reservation-fe#1]
## To-do
- [ ] @syeonee 와 분석할 화면 나누기
- [ ] 각 화면별 분석 결과 wiki 작성
- [ ] 개발할 기능 단위 쪼개서 이슈 작성
- [ ] 개발 계획 세우기
## 참고사항
- 개발 계획은 마일스톤 활용
- 프로젝트 TODO에 추가
